import { sql } from 'drizzle-orm';
import { customType, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Column helpers shared by every table. Names are camelCase here and snake_case in SQL
 * (`casing: 'snake_case'` in both drizzle-kit and the runtime client).
 */

/** Case-insensitive text (the `citext` extension): slugs and email addresses. */
export const citext = customType<{ data: string }>({
  dataType: () => 'citext',
});

/** Raw bytes: hashes and encrypted secrets. */
export const bytea = customType<{ data: Buffer; default: false }>({
  dataType: () => 'bytea',
});

/** Time-ordered UUIDv7 primary key, generated by `app.uuidv7()` (native `uuidv7()` on PostgreSQL 18). */
export const uuidPk = () =>
  uuid()
    .primaryKey()
    .default(sql`app.uuidv7()`);

/** An instant, always stored in UTC. */
export const instant = () => timestamp({ withTimezone: true, mode: 'date' });

export const createdAt = () => instant().notNull().defaultNow();

/** Maintained by the `app.touch_updated_at` trigger; the default covers the insert. */
export const updatedAt = () => instant().notNull().defaultNow();

/**
 * A fractional-index position (board columns, cards, subtasks). Byte order (`COLLATE "C"`) is the
 * order `fractional-indexing` generates keys in; a locale collation would sort them differently.
 */
export const position = customType<{ data: string }>({
  dataType: () => 'text COLLATE "C"',
});
