import type { AgendaEntry, Task } from '@/types';
import { expandOccurrences } from '@/lib/recurrence';

export interface DayBucket {
  /** Tasks due that day that are not yet done. */
  readonly pending: readonly Task[];
  readonly completed: readonly Task[];
  /** Occurrences generated by a recurrence rule rather than the task's own due date. */
  readonly recurring: readonly Task[];
  readonly entries: readonly AgendaEntry[];
}

export type DayIndex = ReadonlyMap<string, DayBucket>;

const emptyBucket = (): DayBucket => ({ pending: [], completed: [], recurring: [], entries: [] });

/**
 * Builds an ISO-date → bucket map for the visible window.
 *
 * Recurring tasks are expanded through the same Jalali engine the board uses, so a
 * fortnightly review shows on every occurrence inside the month rather than only on its
 * original due date. The first occurrence is the task's own due date and is counted once,
 * under pending/completed rather than under `recurring`.
 */
export function buildDayIndex(
  tasks: readonly Task[],
  entries: readonly AgendaEntry[],
  windowStartIso: string,
  windowEndIso: string,
): DayIndex {
  const index = new Map<string, DayBucket>();

  const bucketFor = (iso: string): DayBucket => {
    const existing = index.get(iso);
    if (existing) return existing;
    const created = emptyBucket();
    index.set(iso, created);
    return created;
  };

  const push = (iso: string, key: keyof DayBucket, value: Task | AgendaEntry) => {
    if (iso < windowStartIso || iso > windowEndIso) return;
    const bucket = bucketFor(iso);
    index.set(iso, { ...bucket, [key]: [...bucket[key], value] } as DayBucket);
  };

  for (const task of tasks) {
    push(task.dueDate, task.status === 'done' ? 'completed' : 'pending', task);

    if (task.recurrence) {
      // Skip index 0 — that is the task's own due date, already counted above.
      for (const iso of expandOccurrences(task.dueDate, task.recurrence, windowEndIso).slice(1)) {
        push(iso, 'recurring', task);
      }
    }
  }

  for (const entry of entries) {
    push(entry.date, 'entries', entry);
  }

  return index;
}

export function bucketAt(index: DayIndex, iso: string): DayBucket {
  return index.get(iso) ?? emptyBucket();
}

export function bucketTotal(bucket: DayBucket): number {
  return bucket.pending.length + bucket.completed.length + bucket.recurring.length + bucket.entries.length;
}
